version: '3.9'
name: 'nuxt-app'
services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine3.19
    restart: always
    environment:
      POSTGRES_DB: 'nuxt_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: