export const channels = [
  {
    id: 15134536,
    title: "Коток|коготоК - канал для самых любимых котиков",
    description: "Канал про котиков, которые любят все люди",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 34,
  },
  {
    id: 15234536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 35,
  },
  {
    id: 15334536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 36,
  },
  {
    id: 15344536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 37,
  },
  {
    id: 15345536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 38,
  },
  {
    id: 15634536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 39,
  },
  {
    id: 15374536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 40,
  },
  {
    id: 15384536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 41,
  },
  {
    id: 15394536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 42,
  },
  {
    id: 11534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 43,
  },
  {
    id: 21534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 44,
  },
  {
    id: 13534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 45,
  },
  {
    id: 12534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 46,
  },
  {
    id: 123534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 47,
  },
  {
    id: 14534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 48,
  },
  {
    id: 15534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 49,
  },
  {
    id: 16534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 50,
  },
  {
    id: 17534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 51,
  },
  {
    id: 18534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 52,
  },
  {
    id: 19534536,
    title: "Коток|коготоК",
    description: "Канал про котиков",
    username: "@kotokogotok",
    image: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    inviteLink: "https://t.me/kotok",
    owner: 53,
  },
];
